kind: Service
apiVersion: v1
metadata:
  name: customerservice
  labels:
    app: customerservice
spec:
  type: LoadBalancer
  selector:
    app: customerservice
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: customerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerservice
  template:
    metadata:
      labels:
        app: customerservice
        version: v1
    spec:
      containers:
      - name: customerservice
        image: fra.ocir.io/ateamsaas/stefan-ocir-public/customerservice:latest
        command: ["java", "-jar"]
        args:
        - "customer-svc.jar"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: ocirsecret
---
