# TODO: Remove this and have it work with OCI Vault
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret }}
  namespace: {{ .Release.Namespace }}
data:
  {{ include "orderservice.imagePullSecret" .Values.imageCredentials }}
type: kubernetes.io/dockerconfigjson
