# TODO: Remove this and have it work with OCI Vault
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.userApp.secrets.atp.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  adminUser: {{ .Values.userApp.secrets.atp.adminUser | b64enc  }}
  adminPassword: {{ .Values.userApp.secrets.atp.adminPassword | b64enc  }}
  dbName: {{ .Values.userApp.secrets.atp.dbName | b64enc  }}
  dbUrl: {{ .Values.userApp.secrets.atp.dbUrl | b64enc }}
  serviceUser: {{ .Values.userApp.secrets.atp.serviceUser | b64enc  }}
  servicePassword: {{ .Values.userApp.secrets.atp.servicePassword | b64enc  }}
type: Opaque
---
# TODO: Remove this and have it work with OCI Vault
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.userApp.secrets.atp.walletSecretName }}
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "deps/atp/*").AsSecrets | indent 2 }}
type: Opaque
---
# TODO: Remove this and have it work with OCI Vault
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.userApp.secrets.atp.scriptSecretName }}
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "deps/init.sql").AsSecrets | indent 2 }}
type: Opaque