apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-spectra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello-spectra.labels" . | nindent 4 }}
spec:
  replicas: {{ include "hello-spectra.tShirtSize" .Values.tShirtSize }}
  selector:
    matchLabels:
      {{- include "hello-spectra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-spectra.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      serviceAccountName: {{ include "hello-spectra.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["java", "-jar"]
          args:
          - "hello-spectra.jar"
          ports:
            - name: http
              containerPort: {{ .Values.microservice.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello
              port: {{ .Values.microservice.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.microservice.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}